---
- name: Glances Setup
  hosts: all
  become: yes
  gather_facts: True
  pre_tasks:
    - name: Require Python for Glances
      raw: test -e /usr/bin/python || test -e /usr/bin/python
      changed_when: False
#  roles:
#    - python
  tasks:
    - name: Install Pip
      yum:
        name: python-pip
        state: latest
    - name: Start glances server in the background
      shell: pip install glances
    - name: Start glances server in the background
      shell: nohup glances -w -p 8083 </dev/null >/dev/null 2>&1 &
